### ISSUE TITLE
Portrayal registry UI does not conform to S-100 Part 2b

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S100Infrastructure#1]
S-100 Part 2 clause 2b-4.1 shows the types of items which may be registered. The portrayal registry doesn't show all of these items in its user interface (UI). Additionally, the UI shows some items which are no longer present in Part 2b.

![image](https://github.com/iho-ohi/S100Infrastructure/assets/62906211/a5665320-69ed-4762-b263-25e88bb502be)

### Portrayal Catalog Items
|Item|Registry UI|S-100 Part 2b|
|:---|:---:|:---:|
|Alert|N|Y
|Alert Highlight|N|Y
|Alert Message|N|Y
|Area Fill|Y|Y
|Cascading Style Sheet|Y|N
|Color Palette|N|Y
|Color Profile|Y|N
|Color Token|Y|Y
|Color Value|N|Y
|Context Parameter|Y|Y
|Display Mode|Y|Y
|Display Plane|Y|Y
|Display (should be "Drawing") Priority|Y|Y
|Font|Y|Y
|Line Style|Y|Y
|Pixmap|Y|Y
|Symbol|Y|Y
|Viewing Group|Y|Y
|Viewing Group Layer|Y|Y

### Schemas
These are not being maintained as far as I can tell.
|Item|Registry UI|S-100 Part 2b|
|:---|:---:|:---:|
|Area Fill Schema|Y|Y
|Colour Profile Schema|Y|Y
|Linestyle Schema|Y|Y
|Pixmap Schema|Y|Y
|Symbol Schema|Y|Y

**Comment by iho-ohi** [comment]
The Portrayal register has been updated as reported in this issue.

**Comment by DavidGrant-NIWC** [comment]
Please re-open this issue, from the above table both `Color Value` and `Pixmap` are still missing from the UI.

![image](https://github.com/iho-ohi/S100Infrastructure/assets/62906211/d8e5efaf-1b17-4c5c-a914-b768f242fb1b)
