### ISSUE TITLE
GI Registry - VG Retirement - Can't populate field value that is mandatory to 'Submit' a change

### ISSUE THREAD

**Issue by alvarosanuy** [iho-ohi/S100Infrastructure#10]
![image](https://github.com/iho-ohi/S100Infrastructure/assets/70189016/0ad4cbcc-f14f-4f5d-a2c5-ef9083bf7ec3)

**Comment by iho-ohi** [comment]
It is not an issue for the Infra systems or procedures. It is Database issue that it was initially migrated to the database without a definition. The clarification proposal has been submitted for the definition. If approved by DCB, the retirement can be processed. 
This issue is closed.
