### ISSUE TITLE
S-100 Viewer (ver. 1.0.22) crashing and closing when loading data

### ISSUE THREAD

**Issue by jrhee01** [iho-ohi/S100Infrastructure#19]
Upon attempting to open a dataset, FC, and PC, the KHOA S-100 Viewer (version 1.0.22) appears to try loading the data for several seconds, before crashing and closing.

No error messages nor logs appear to be recorded.

I attempted this with S-129 data. It looks as though the same behaviour might be presenting for other products, but not entirely sure.

Great if this could be looked into, to determine if there's an issue with the input data, to the Viewer, or both.

Please let me know if more information is required,

Many Thanks.

**Comment by jrhee01** [comment]
If this issue should instead be raised in "https://github.com/S-100ExpertTeam/khoa-s100-viewer", please let me know, and I will raise it there.
Apologies if this was not the right place, and if I had caused ant confusion.

Thanks.

**Comment by jrhee01** [comment]
Also observed that, when the S-129 FC file and PC folder were copied to the ProgramData folder, and the subsequent paths added to BasicFilePath.txt, the S-100 Viewer no longer starts up.
When the Viewer was re-run after removing the S-129 paths from BasicFilePath.txt, the Viewer starts up again.

**Comment by gorogara** [comment]
@jrhee01 
Tested with the latest FC/PC version on GitHub. 
Please test it, and if the error occurs again, send the data(FC, PC) where the error occurs as well.
[http://gofile.me/3GjXm/r9V2XhDwc](http://gofile.me/3GjXm/r9V2XhDwc)

**Comment by iho-ohi** [comment]
The issue transferred to the Viewer Github, This issue has been closed.

**Comment by iho-ohi** [comment]
The issue transferred to the Viewer Github, This issue has been closed.
