### ISSUE TITLE
Concerns on current xmlID implementation in the GI Registry

### ISSUE THREAD

**Issue by alvarosanuy** [iho-ohi/S100Infrastructure#2]
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/9

**Concerns on current xmlID implementation in the GI Registry raised by @DavidGrant-NIWC below:**

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/asanchez/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/asanchez/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/asanchez/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/asanchez/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-AU link="#0563C1" vlink="#954F72" style='tab-interval:36.0pt'>

<p class=MsoNormal style='mso-outline-level:1'><b><span lang=EN-US
style='mso-ligatures:none;mso-ansi-language:EN-US'>From:</span></b><span
lang=EN-US style='mso-ligatures:none;mso-ansi-language:EN-US'> Grant, David M
(52400) CIV USN NIWC ATLANTIC VA (USA) &lt;<a
href="mailto:david.m.grant22.civ@us.navy.mil">david.m.grant22.civ@us.navy.mil</a>&gt;
<br>
<b>Sent:</b> Saturday, 27 January 2024 5:39 AM<br>
<b>To:</b> Sanchez, Alvaro MR &lt;<a href="mailto:alvaro.sanchez@defence.gov.au">alvaro.sanchez@defence.gov.au</a>&gt;;
Jeff Wootton (IHO) &lt;<a href="mailto:jeff.wootton@iho.int">jeff.wootton@iho.int</a>&gt;<br>
<b>Cc:</b> <a href="mailto:Hugh.Astle@Teledyne.com">Hugh.Astle@Teledyne.com</a>;
Stamenkovich, Miroslav (52400) CIV USN NIWC ATLANTIC SC (USA) &lt;<a
href="mailto:miroslav.stamenkovich.civ@us.navy.mil">miroslav.stamenkovich.civ@us.navy.mil</a>&gt;<br>
<b>Subject:</b> xmlID values<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>We have an
action to update the S-101 PC to use the xmlID values from the registry to
ensure portrayal catalogs can work with one another (the same concept uses the
same lookup in different PC’s).<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>Before I do
this, should I use the currently registered xmlID’s which appear to be random
numbers? For instance, the xmlID for viewing group 11050 is “915”. The xmlID
for the over radar display plane is “1503”. My preference would be to have
meaningful identifiers to make the PC easier to read and maintain.<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><o:p>&nbsp;</o:p></span></p>

Item | Current xmlID | Suggested xmlID
-- | -- | --
Viewing Group 11050 | “915” | “11050”
Display Plane over radar | “1503” | “OverRADAR”
Display mode “Display Base” | “927” | “DisplayBase”
Context parameter “Safety Depth” | “1459” | “SafetyDepth”

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>These xmlID
values correspond to the “id” values embedded in PC’s. They are used to
identify catalog entries:<o:p></o:p></span></p>

</body>

</html>

![xczx](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/26dc40bb-ab7d-405d-a23b-56fa57a18ef6)

![image](https://github.com/iho-ohi/S100Infrastructure/assets/70189016/c50fd411-c7eb-4524-9784-adc976c77540)

![image](https://github.com/iho-ohi/S100Infrastructure/assets/70189016/db3dc7fc-f8bd-4404-ab36-aaec9870ca1f)

**Comment by iho-ohi** [comment]
This requirement is now listed on the KHOA's project to update the interface of the GI registry.
There are two issues that I understood:
 1. Interface: to allow character string in the xmlID (Aa-Az, _, 0-9)
 2. Update contents: incomplete and incorrect

 - No.1, please confirm the constraints as above. If the interface updated, who will update the contents with which format, PR_1234 or ? any impact?
 - No.2, regarding the update to the contents, it should be processed via the proposal.

Please response your confirmation or comment by 12 April 2024.

**Comment by DavidGrant-NIWC** [comment]
> 1. Interface: to allow character string in the xmlID (Aa-Az, _, 0-9)
[...]
No.1, please confirm the constraints as above.

Recommend that underscore is not used (even if allowed) because the current portrayal catalog schema doesn't allow it in the definition of _CatalogItem_. Underscores may be allowed in future revisions of the portrayal catalog schema; the interface should not preclude their future use.

**Comment by iho-ohi** [comment]
In terms of the interface of the portrayal register, it has been updated as we agreed.

**Comment by DavidGrant-NIWC** [comment]
> No.2, regarding the update to the contents, it should be processed via the proposal.

We need a registry proposal to update the xmlID of every viewing group / viewing group layer / etc., and also to update the xmlID's of any entries which might currently conflict with those proposed changes?
