### ISSUE TITLE
KHOA Symbol Editor bug

### ISSUE THREAD

**Issue by RichardCoyles** [iho-ohi/S100Infrastructure#4]
I've created symbols for Emergency Wreck and Safe Water marks

https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/158

but every time I load up the symbols in the KHOA Symbols Editor, the circle highlighted is off centre. I move the circle back to its correct position and save. When I load it again it has shifted off centre.

![image](https://github.com/iho-ohi/S100Infrastructure/assets/108347351/8ba03db7-b5ea-4cfc-b3a2-27ffb822707e)

![BOYSPH01](https://github.com/iho-ohi/S100Infrastructure/assets/108347351/3d64f2d0-0c6e-422d-a19c-b6d49d46133a)
![BOYSPH60](https://github.com/iho-ohi/S100Infrastructure/assets/108347351/43f5eb85-43cd-4330-bcdc-53c9620d54af)

Ive attached an example .svg created above  (BOYSPH60) and the symbol I based this on (BOYSPH01)

Suggestions to rectify or testing to confirm my findings welcome.

It may be user error!

Many thanks

Richard - UKHO

**Comment by MikusRL** [comment]
@RichardCoyles the files (svgs?) you attaches are not downloadable. Please usually zip files before uploading to GitHub. But I would suggest you check the symbol portraying in the web browser (use the mentioned .css file in the svg). Also load in like a Notepad++ to see if nothing is wrong in characters and lines. Then it would be more possible to point if the issue is in the Symbol Builder, and when it occurs - at loading of the symbol, or at saving the symbol. Then the issue hopefully could be fixed. 

It was my experience with earlier versions of Symbol Builder, that it by default would overwrite quite a few lines in the header, even if you load your own already almost finished symbol encoding. That was reported to them back through IHO secretariat that it should not happen like that with already existing svgs being loaded for just some small adjustments. I have not tested if this still is the case in the latest version. But could be worth checking also in your case, if any values or lines does not suddenly default to something predefined once the svg is loaded.

**Comment by bluemap-git** [comment]
@RichardCoyles 
Please upload as a zip file, as mentioned.

**Comment by RichardCoyles** [comment]
[cvnhn.zip](https://github.com/iho-ohi/S100Infrastructure/files/14740564/cvnhn.zip)

As requested, many thanks for suggestions thus far.

**Comment by RichardCoyles** [comment]
.

**Comment by RichardCoyles** [comment]
![BOYSPH60](https://github.com/iho-ohi/S100Infrastructure/assets/108347351/c7c48051-06dc-4bed-9f54-94e65ba5bf60)
![BOYSPH01](https://github.com/iho-ohi/S100Infrastructure/assets/108347351/c2fd7a8a-8be5-4914-a863-4724376a2024)

**Comment by RichardCoyles** [comment]
![BOYSPH01](https://github.com/iho-ohi/S100Infrastructure/assets/108347351/d62b0b30-01e1-4046-a18f-f9b660144f71)

**Comment by RichardCoyles** [comment]
[BOYSPH01](https://github.com/iho-ohi/S100Infrastructure/assets/108347351/cf89b383-2099-4050-b185-37ee49bcedff)
[BOYSPH60](https://github.com/iho-ohi/S100Infrastructure/assets/108347351/d620b17e-2918-4f08-b085-f78473209884)

**Comment by gorogara** [comment]
@RichardCoyles 
There was an issue with the Symbol Editor, when the radius of the Circle changed to an ellipse, it was being saved as a Path.
So, there was an error where the location was changed when loading again.
The sky-blue circle in the file you sent was slightly elliptical.
I've changed the sky-blue circle to a perfect circle and attached it.
Symbol Editor is scheduled to support S-100 5.2.0 and there seems to be a lot of changes.
When updated, you will be able to use the Ellipse command immediately, so this kind of problem will not occur.
Please check the attached file.
![test1](https://github.com/iho-ohi/S100Infrastructure/assets/5345308/4b163ae4-7749-4ec6-bdff-4fbc8815ef9a)
`<?xml version="1.0" encoding="utf-8" standalone="yes"?> <?xml-stylesheet href="SVGStyle.css" type="text/css"?> <svg xmlns="http://www.w3.org/2000/svg" version="1.2" baseProfile="tiny" xml:space="preserve" style="shape-rendering:geometricPrecision; fill-rule:evenodd;" width="7.65mm" height="6.91mm" viewBox="-3.78 -5.39 7.65 6.91"> <title>BOYSPH60</title> <desc>spherical buoy, paper-chart</desc> <metadata> <iho:S100SVG xmlns:iho="http://www.iho.int/SVGMetadata"> <iho:Description publisher="IHO" creationDate="2024-03-26" source="S52Preslib4.0" format="S100SVG" version="0.1" /> </iho:S100SVG> </metadata> <circle class="pivotPoint layout" fill="none" cx="0.00" cy="0.00" r="0.4" /> <rect class="symbolBox layout" fill="none" x="-3.78" y="1.52" height="6.91" width="7.65" /> <rect class="svgBox layout" fill="none" x="-3.78" y="-5.39" height="6.91" width="7.65" /> <circle cx="-0.01" cy="-0.01" r="0.51" class="fCHWHT" style="stroke-width:0.64;fill-opacity:1.0;" /> <path d=" M 0.54,0 L 0.47,-0.25 L 0.32,-0.44 L 0.14,-0.51 L 0.01,-0.52 L 0.13,-4.38 L 0.4,-4.38 L 0.98,-4.25 L 1.6,-3.97 L 2,-3.65 L 2.32,-3.17 L 2.61,-2.71 L 2.8,-2.19 L 2.83,-1.61 L 2.78,-0.91 L 2.56,-0.39 L 2.33,-0.02 L 0.55,-0.01 L 0.54,0" class="fCHYLW" style="stroke-width:0.64;fill-opacity:1.0;" /> <path d=" M -0.54,0 L -2.2,0 L -2.47,-0.71 L -2.63,-1.85 L -2.5,-2.5 L -2.31,-2.96 L -1.98,-3.4 L -1.6,-3.77 L -1.14,-4.09 L -0.69,-4.26 L -0.17,-4.38 L 0.14,-4.39 L 0.02,-0.51 L -0.39,-0.37 L -0.54,0" class="fRESBL" style="stroke-width:0.64;fill-opacity:1.0;" /> <circle cx="0" cy="0" r="0.52" class="sl f0 sCHBLK" style="stroke-width:0.64;" /> <path d=" M 0.56,0 L 2.87,0" class="sl f0 sCHBLK" style="stroke-width:0.64;" /> <path d=" M -2.19,0 L -2.47,-0.69 L -2.56,-1.25 L -2.63,-1.85 L -2.5,-2.5 L -2.31,-2.97 L -1.97,-3.41 L -1.59,-3.79 L -1.13,-4.1 L -0.69,-4.25 L -0.16,-4.38 L 0.41,-4.38 L 0.97,-4.25 L 1.59,-3.97 L 2,-3.66 L 2.28,-3.25 L 2.62,-2.72 L 2.81,-2.19 L 2.84,-1.6 L 2.78,-0.88 L 2.56,-0.38 L 2.33,0" class="sl f0 sCHBLK" style="stroke-width:0.64;" /> <path d=" M -2.78,0 L -0.52,0" class="sl f0 sCHBLK" style="stroke-width:0.64;" /> </svg>`
![image](https://github.com/iho-ohi/S100Infrastructure/assets/5345308/22f30147-4064-45db-b1f2-d197b5762520)

**Comment by RichardCoyles** [comment]
Many thanks for this! I was looking for the function that would allow to increase the size of the circle and keep it round, rather than becoming elliptical, while holding down the shift of fn or ctrl, but couldn't find it.

Thanks again for all you work on the KHOA Editor - 

Richard - UKHO

**Comment by RichardCoyles** [comment]
closed , thanks
