### ISSUE TITLE
Logging in the S-100 Launcher for the Toolkit

### ISSUE THREAD

**Issue by MikusRL** [iho-ohi/S100Infrastructure#5]
I can not log in the S-100 Launcher of the Toolkit. I am pretty sure I remember the password correctly. Is there any issues with logging in the system? I can log in in the web page in the GI Registry with no problem with my credentials. There was earlier similar issue with the S-100 Toolkit Launcher back in time, but it was happening once one set to ON the Save ID. Now I have not done that and it seems something goes wrong in the launcher with the logging in anyway. 

![image](https://github.com/iho-ohi/S100Infrastructure/assets/72803214/02ed3de5-87d8-49b5-b1e9-86afb64abf3f)

**Comment by bluemap-git** [comment]
@MikusRL 
There is a problem with the login server right now.
We are working on resolving it. We will inform you once it is resolved.

**Comment by iho-ohi** [comment]
The primary issue has been resolved; however, certain technical risks remain. These will be subject to further investigation to facilitate their resolution and enhance the system's performance.
Please re-open the issue should it occur again.

**Comment by MikusRL** [comment]
I can log in now, but I do not see any tools in the main window to launch. 
![image](https://github.com/iho-ohi/S100Infrastructure/assets/72803214/64225d0b-ab52-4aad-9f2f-ccafd94d9958)

Is there a newer version Toolkit to be installed?

**Comment by gorogara** [comment]
![image](https://github.com/iho-ohi/S100Infrastructure/assets/5345308/c7a965d4-e1a7-47aa-b03e-6e223a134722)
@MikusRL 
Recently, the server has been intermittently not working properly.
Restarting server solves the problem, but we are still looking for the fundamental reason.
For now, we have made it work properly.

**Comment by MikusRL** [comment]
@gorogara Thank you for the fixes. Now I have again all the tools. I had to install though all the tools. But it looked like from the version numbers, that I kind of had all the latest versions. But by the version date it looked that it is newer and should be installed. 
Now I have the launcher up and running, thank you. 

If you are happy as well, feel free to close this case. Thanks.
