### ISSUE TITLE
Not able to select VGL from drop down menu

### ISSUE THREAD

**Issue by alvarosanuy** [iho-ohi/S100Infrastructure#6]
When trying to update an existing VG (Supersession) in the GI registry, I can't enter a value for VGL field (which is mandatory). Consequently, I can't 'Submit' the changes.

![image](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/assets/70189016/3ecedec4-06a0-427f-8d7c-184efeaee29f)

**Comment by iho-ohi** [comment]
It's been fixed. Please try to do and let close the issue if confirmed. Otherwise, leave comment and/or create another issue if raised other problem.

**Comment by alvarosanuy** [comment]
I was able to press 'Submit' the change proposal but I was not able to select a VGL (!?). This needs to be fixed at some point.
recommend leaving this issue open until the use of the VGL field is better understood. I was planning to enter 2.

**Comment by iho-ohi** [comment]
The issue selecting the VGL has been fixed. Please try to do it. If it is resolved, close the issue.
